### ISSUE TITLE
Nested value is null when using the default `fetchPolicy` on `QueryOptions`

### ISSUE THREAD

**Issue by ming-chu** [zino-hofmann/graphql-flutter#950] opened 2021-08-03 05:10 UTC
**Describe the issue**
Nested value is missing when using the default `fetchPolicy` on `QueryOptions`.

**To Reproduce**
```dart
import 'dart:convert';
import 'package:flutter_test/flutter_test.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:http/http.dart' as http;
import 'package:gql/language.dart';
import 'package:mockito/mockito.dart';

void main() {
  group('GraphQL', () {
    late MockClient httpClientMock;
    late GraphQLClient client;

    setUp(() {
      httpClientMock = MockClient();
      client = GraphQLClient(
        link: HttpLink('', httpClient: httpClientMock),
        cache: GraphQLCache(store: InMemoryStore()),
      );
    });

    test('QueryOptions default fetchPolicy', () async {
      final String usersQuery = r'''
        query Users() {
          users() {
            ...userRes
          }
        }
        fragment userRes on Edges {
          edges {
            cursor
            node {
              userId
              name
            }
          }
        }
        ''';

      final _options = QueryOptions(
        document: parseString(usersQuery),
        variables: {},
        // fetchPolicy: FetchPolicy.noCache, // it's working when using noCache
      );

      final result = await client.query(_options);

      print(result.data);
      expect(result.data!['users'], isNotNull);
      expect(result.data!['users']['edges'], isNotNull);
    });
  });
}

class MockClient extends Mock implements http.Client {
  MockClient({
    this.mockedResult,
    this.mockedStatus = 200,
  });
  final Map<String, dynamic>? mockedResult;
  final int mockedStatus;

  final mockResponseDict = {
    "data": {
      "users": {
        "edges": [
          {
            "cursor": "1",
            "node": {
              "userId": "abc123",
              "name": "MC",
            }
          },
        ]
      }
    }
  };

  @override
  Future<http.StreamedResponse> send(http.BaseRequest? request) {
    return Future<http.StreamedResponse>.value(
      http.StreamedResponse(
        Stream.value(utf8.encode(jsonEncode(mockResponseDict))),
        200,
      ),
    );
  }
}

```

**Expected behavior**
Expected the nested value is not null.

**screenshots**
![image](https://user-images.githubusercontent.com/12498885/127960839-f6867e1b-ff0c-471f-95fc-906d3f3f7322.png)

Thanks for the help. 

Very appreciated everyone's contribution/help to this project.❤️

**Comment by jerryzhoujw** [comment] 2021-08-10 09:16
it's caused by `fragment`, don't use fragment that for now.

**Comment by ming-chu** [comment] 2021-08-10 09:21
@jerryzhoujw  Thanks for the reply. Is that the bug of the plugin or I used it in a wrong way?

**Comment by angelorobo** [comment] 2021-08-10 09:25
It is the bug. We're seeing the same issue when using `fragment`

**Comment by ming-chu** [comment] 2021-08-10 09:31
@angelorobo Noted and thanks! Will avoid using `fragment` before it fixes. (my fragments are used around the queries haha) Thanks!

**Comment by ming-chu** [comment] 2021-08-11 23:46
I also found that it's working fine if the responses directly from network without touching the cache. Hope this can help.

**Comment by rynoV** [comment] 2021-08-20 17:43
I'm also running into this. Using `fetchPolicy: FetchPolicy.noCache` in my `QueryOptions` works around the issue.

**Comment by jlabeit** [comment] 2022-02-09 21:57
> it's caused by `fragment`, don't use fragment that for now.

I also run into this. Is there a special issue to track this (e.g. to track if fragments can be be used properly)?

**Comment by vincenzopalazzo** [comment] 2022-02-09 23:04
@jlabeit What is your library version?

Do you have a reproducible example? I think this issue is fixed already in the actual beta.

**Comment by budde377** [comment] 2022-02-10 06:19
@jlabeit  As @vincenzopalazzo mentions, this should be fixed in the latest beta. Please try this out and feel free to refer to the [README](https://github.com/zino-hofmann/graphql-flutter/tree/beta/packages/graphql#normalization) for more details on setting up your client correctly. 

If you're using code-generation, we've also seen some problems with Artemis, consider switching to `graphql_codegen`.

**Closed by budde377** 2022-02-10 06:19 UTC
Labels: :bug: bug
