### ISSUE TITLE
Unhandled Exception: Exception: Unable to resolve data ID for type GalleryImageView (type in fragment), Please ensure that you are passing the correct ID fields

### ISSUE THREAD

**Issue by KhizarShabir1** [zino-hofmann/graphql-flutter#991] opened 2021-12-16 09:12 UTC
The code present below is simillar to the on the one present in [this](https://github.com/zino-hofmann/graphql-flutter/blob/f76053a04d7ff62db5e3c0f6c9e22c91d8932648/packages/graphql_flutter/example/lib/graphql_widget/main.dart) file on the **171** line but I am having this error when I run the code for this mutation.

Error:
VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Exception: Unable to resolve data ID for type GalleryImageView. Please ensure that you are passing the correct ID fields

```  
Map<String, dynamic>? extractRepositoryData(Map<String, dynamic?> data) {
    final action = data["deleteImage"] as Map<String, dynamic>?;
    return action;
  }
  
  OnMutationUpdate get update => (cache, result) {
    if (result!.hasException) {
      print(result.exception);
    } else {
      final updated = {

        ...extractRepositoryData(result.data!)!,
      };
     
      cache.writeFragment(
        Fragment(
          document: gql(
            '''
                  fragment fields on GalleryImageView {
                    id
                    deleted
                  }
                  ''',
          ),
        ).asRequest(idFields: {
          '__typename': updated["__typename"],
          'id': updated["id"],
        }),
        data: updated,
      );
    }
  };


  Future<QueryResult> performMutationDelete(String query, {var variables, Function? refetchQuery}) async {
    // variables is type Map<String, dynamic>
    MutationOptions options = MutationOptions(
        document: gql(query),
        update: update,
        variables: variables ?? {},
        onCompleted: (onValue) {
          if (refetchQuery != null) {
            refetchQuery();
          }
        });

    final result = await clientFor().value.mutate(options);

    return result;
  }
```
Here is the details of the data that I am getting in the mutation:

 flutter: {__typename: Mutation, deleteImage: {__typename: GalleryImageView, id: 10, deleted: true}}

**Comment by vincenzopalazzo** [comment] 2021-12-16 19:33
What is the `GalleryImageView` data model?

**Comment by KhizarShabir1** [comment] 2021-12-17 23:20
`GalleryImageView` is the type that I am mutating, like the ´MyType´ in the explanation of direct cache access ([here.](https://github.com/zino-hofmann/graphql-flutter/blob/master/packages/graphql/README.md#fragmentrequest-readfragment-and-writefragment))

**Comment by vincenzopalazzo** [comment] 2021-12-18 11:07
>@vincenzopalazzo GalleryImageView is the type that I am mutating, like the MyType in the explanation of direct cache access (here.)

It is a custom type, and what I want to make sure is that `YourType` has also your Filed. More concrete `GalleryImageView` has type `id`?

**Comment by KhizarShabir1** [comment] 2021-12-18 12:34
yes GalleryImageView has type id and the value of id here is `10`. 
`{__typename: Mutation, deleteImage: {__typename: GalleryImageView, id: 10, deleted: true}}`

**Comment by vincenzopalazzo** [comment] 2021-12-18 12:50
I will try to reproduce it in the next few days!

**Comment by vincenzopalazzo** [comment] 2022-04-09 08:41
Was unable to reproduce it! Closing for now, until we have no a good example to catch the bug

**Closed by vincenzopalazzo** 2022-04-09 08:41 UTC
Labels: :hourglass: reproduction needed
