### ISSUE TITLE
the demo "starwars" doesn't work because websocket_client

### ISSUE THREAD

**Issue by mashihao** [zino-hofmann/graphql-flutter#1058] opened 2022-03-04 03:15 UTC
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/graphql-5.0.1/lib/src/links/websocket_link/websocket_client.dart:208:9: Error: The method 'unawaited' isn't defined for the class 'SocketClient'.
 - 'SocketClient' is from 'package:graphql/src/links/websocket_link/websocket_client.dart' ('../../../../flutter/.pub-cache/hosted/pub.dartlang.org/graphql-5.0.1/lib/src/links/websocket_link/websocket_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'unawaited'.
        unawaited(_closeSocketChannel());
        ^^^^^^^^^

**Comment by manuelduarte077** [comment] 2022-07-21 06:56
reviewing this error, I think it would be good to add more examples using this packages I have a while to use it, I have some on my github, I have examples using artemis to generate the static classes in dart based on my graphql shema, and after that I have those classes I do the magic with this package 😎

https://github.com/manuelduarte077/pokemon_graphql

**Comment by vincenzopalazzo** [comment] 2022-07-21 10:21
The problem is that you are using a public API and the public API died somehow, like in the case of the prev example!

The optimal idea is to provide an example with the API, and these API are used inside the test too.

And all the tests are possible to reproduce with a docker image not only in the CI, because the CI dies somehow (e.g travis)

Working on this idea https://github.com/zino-hofmann/graphql-flutter/issues/1162#issuecomment-1182946910

In addition, closing this issue because there is already a discussion https://github.com/zino-hofmann/graphql-flutter/discussions/1165

P.S: You can add your message here :)

**Closed by vincenzopalazzo** 2022-07-21 10:21 UTC
Labels: help wanted, :hatching_chick: good first issue, :bullettrain_side: doc & examples, new contributors, Priority: Low

**Comment by mashihao** [comment] 2022-07-22 02:08
> The problem is that you are using a public API and the public API died somehow, like in the case of the prev example!
> 
> The optimal idea is to provide an example with the API, and these API are used inside the test too.
> 
> And all the tests are possible to reproduce with a docker image not only in the CI, because the CI dies somehow (e.g travis)
> 
> Working on this idea [#1162 (comment)](https://github.com/zino-hofmann/graphql-flutter/issues/1162#issuecomment-1182946910)
> 
> In addition, closing this issue because there is already a discussion #1165
> 
> P.S: You can add your message here :)

Thank you very much for your reply
