### ISSUE TITLE
Fragments stopped working after graphql update

### ISSUE THREAD

**Issue by asmodeoux** [zino-hofmann/graphql-flutter#994] opened 2021-12-17 13:40 UTC
**Describe the issue**
I updated graphql package from 3.1.0 to 4.0.1 and now GraphQL responses with fragments are not operated correctly. Here is an example on StackOverflow: https://stackoverflow.com/questions/70393062/json-fails-to-parse-graphql-response-after-flutter-libs-upgrade

I'm not sure if it's related directly to graphql update or is there something wrong with parsing the response with json libraries, but I hope anyone here knows what's going wrong. I checked all the changelogs and docs and didn't find any info about that.

**To Reproduce**
1. Update graphql from 3.1.0 to 4.0.1
2. Make a fresh build after flutter clean & updating the pods

**Expected behavior**
Old documents are working correctly and everything works as well as on 3.1.0

**Actual behavior**
Documents with fragments don't parse correctly anymore

**device / execution context**
iOS 14/15, also reproducible in Android

**additional context**
All the additional context is available in my StackOverflow post, please check it for code samples and screenshots

**additional notes**
I like everything but I hope it will work for me again :-)

**Comment by vincenzopalazzo** [comment] 2021-12-17 13:49
>I checked all the changelogs and docs and didn't find any info about that.

Maybe because the version that you are using it is the only one, there is a beta version available here https://pub.dev/packages/graphql/versions/5.0.1-beta.1 can you check with it?

**Comment by asmodeoux** [comment] 2021-12-17 14:19
@vincenzopalazzo I've just checked and 5.0.1-beta.1 also doesn't work

**Comment by vincenzopalazzo** [comment] 2021-12-17 14:22
Mh, interesting. Any tips to reproduce the error in a local env?

Thanks

**Comment by asmodeoux** [comment] 2021-12-17 14:26
@vincenzopalazzo unfortunately the API I use is private and pretty hard to reproduce since there's authorisation needed. If there's any API you know where you can use fragments in queries you can try that.

**Comment by vincenzopalazzo** [comment] 2021-12-17 14:37
Some app example contains fragments but I need to update them. I will put in my to-do list, but not sure that we can reproduce your error with another API. But we will see

**Comment by alitnk** [comment] 2021-12-24 09:28
I am also getting null when I use fragments.

**Comment by vincenzopalazzo** [comment] 2021-12-24 18:08
@alitnk 

Can you provide an small example? maybe we have a bug somewhere?

**Comment by alitnk** [comment] 2021-12-25 09:35
@vincenzopalazzo 
This is the repository in which I'm facing the issue: https://github.com/matnbaz/matnbaz-mobile, look for `FetchPolicy.noCache` occurrences and try to remove them.

Let me know if this example has too much unrelated code or is just isn't good for testing the problem, I'd gladly make a small example.

And thank you for your time. the library is working perfectly, except for this issue.

**Comment by asmodeoux** [comment] 2021-12-25 09:40
@alitnk Thanks, this noCache workaround helped me as well

**Comment by vincenzopalazzo** [comment] 2021-12-25 11:13
>Let me know if this example has too much unrelated code or is just isn't good for testing the problem, I'd gladly make a small example.

If you can provide a small example will be perfect to me, and we can try to accelerate the debugging of it :) thanks

**Comment by alitnk** [comment] 2021-12-25 14:15
> If you can provide a small example will be perfect to me, and we can try to accelerate the debugging of it :) thanks
 
There you go: https://github.com/alitnk/graphql_flutter_fragments_example

Worth mentioning that I'm using [Artemis](https://github.com/comigor/artemis) in this example, So the query document is auto generated.
 Please mention me if there's an issue with the example repo.

**Comment by vincenzopalazzo** [comment] 2021-12-26 11:41
Amazin, I will prioritize this issue in my queue to prove my gratitude to build this example.

Thanks!

**Comment by micimize** [comment] 2021-12-29 20:48
The newer cache uses `__typename` to intelligently deconstruct and reconstruct the data using the `normalize` library, but it shouldn't try and do anything fancy without it.

1. Add `__typename such as is supplied by the `gql` helper
2. Try supplying [possibleTypes](https://pub.dev/documentation/graphql/latest/graphql/GraphQLCache/possibleTypes.html) to the cache (i.e. `{"Role": {"Client"}}`)
3. See if `normalize` is `0.5.5`. This issue maybe caused by some issue with fragments resolved in `0.5.5` (https://pub.dev/packages/normalize/changelog):
https://github.com/zino-hofmann/graphql-flutter/blob/f0793fd35279bb7948c53ce7204a343dca883705/packages/graphql/pubspec.yaml#L16

Ultimately the cache shouldn't do anything to query objects without `__typename` available to work with or customizations

**Comment by budde377** [comment] 2021-12-30 07:05
@vincenzopalazzo, I've worked on improving how normalize parses fragments (see latest https://github.com/gql-dart/ferry/pull/300). As @micimize suggests, I expect this issue to be caused by this. In the coming versions of normalize, users will need to supply `possibleTypes` to the client. We'll need to update the documentation to reflect this. I'm using `graphql_codegen` to generate these types myself.

**Comment by budde377** [comment] 2021-12-30 10:43
@asmodeoux Please try the following: 

* Add the normalize dependency to version `0.5.3`, exactly.
* Add `__typename` to all your query objects
* Provide `possibleTypes` map. You can generate this with GraphQL codegen (https://pub.dev/packages/graphql_codegen)

**Comment by msal4** [comment] 2022-01-07 16:23
I'm facing the same issue I didnt have it before 5.0. possibleTypes is null for all my types. the `noCache` workaround seems to work but i'd prefer to keep the cache. I'm using artemis btw
I'd appreciate any guidance. Thanks for all your hard work :)

**Comment by vincenzopalazzo** [comment] 2022-01-07 17:55
Hi @msal4,

another solution can be to fix the version  `normalize: 0.5.3`, with [dependeces override](https://dart.dev/tools/pub/dependencies#dependency-overrides) as suggested here

>Add the normalize dependency to version 0.5.3, exactly.

We are working on a solution because normalize as a breaking change in the last version, so we are deciding if we need to work with an old solution or we need to update the doc to support the new one.

Sorry for that

**Comment by msal4** [comment] 2022-01-07 18:09
Hey @vincenzopalazzo, I've already added `normalize: 0.5.3`, still facing the same issue.

**Comment by budde377** [comment] 2022-01-07 19:02
I'm planning on working on this this weekend

**Comment by msal4** [comment] 2022-01-07 20:41
@budde377 great!
yeah i know. I only use artemis for codegen I dont use their client. plus graphql_flutter works better with flutter.

**Comment by budde377** [comment] 2022-01-08 16:16
I've created a PR outlining the steps necessary to get proper fragment resolution with the new version of normalize. 

@alitnk Regarding your example, as far as I can see you're not providing the `possibleTypes` (here: https://github.com/alitnk/graphql_flutter_fragments_example/blob/master/lib/main.dart#L17) or introspection upon fragment spread (e.g. here https://github.com/alitnk/graphql_flutter_fragments_example/blob/master/graphql/queries/get-repositories.graphql#L21).

@msal4 Please check the documentation to see if it makes sense.

**Closed** 2022-01-08 16:18 UTC
Labels: :bug: bug, dart client, :package: cache

**Comment by vincenzopalazzo** [comment] 2022-01-08 16:21
The new release is out https://github.com/zino-hofmann/graphql-flutter/releases/tag/v5.0.1-beta.3

**Comment by msal4** [comment] 2022-01-22 19:16
@budde377 hey, sorry for the late response. I tried doing what you mentioned but still i couldn't get it to work unless i disable cache. I dont have any interfaces defined in my graphql schema and I already have `__typename` in my queries. I'm quite confused tbh.

**Comment by budde377** [comment] 2022-01-22 19:28
@msal4, can you provide a reproducible example of this? 

A repo with your queries, schema, pubspec, and how you're using the client.

**Comment by msal4** [comment] 2022-02-06 13:00
@budde377 Apparently artemis generator doesn't seem to be working with graphql-flutter anymore, haven't checked why exactly but it's something related to the generated queries. I switched to graphql_codegen and everything seems to work just fine.
thanks :)

**Comment by geiszla** [comment] 2022-03-04 12:57
We have a problem with interface fragments that might also be related to this issue.

We have an interface for the user fields called `UserInterface`, and a type called `Self`, which is derived from the `UserInterface`. When we define the fragment as `fragment UserFields on UserInterface` and spread it in another fragment as `fragment SelfFields on Self { ...UserFields }`, on web (using Apollo client) it can correctly return the fields from both the user and self types. On mobile it correctly spreads the fragments and the server returns the fields, but `graphql_flutter` doesn't return it on the result object.

Any ideas on how to solve this?

**Comment by budde377** [comment] 2022-03-04 13:10
As mentioned earlier in this thread, please try and update graphql flutter to the latest version (possibly beta), add __typename if it's not already provided by your query transformer, and supply a possibleTypes map to the client
