### ISSUE TITLE
Subscription not working, only connected

### ISSUE THREAD

**Issue by rrifafauzikomara** [zino-hofmann/graphql-flutter#1361] opened 2023-07-20 03:02 UTC
I am creating a subscription with GraphQL, and I need to consume that subscription with Flutter, but I don't know how to do that on the Flutter side. But I can understand doing that on Postman.

Here are the steps to test a subscription on Postman:
1. Connect to wss
2. Send a `Message` by clicking `Send` button.
3. Trigger any API, then the subscription will listen new data.

And here's the result for above steps.
[![enter image description here][1]][1]

And if I do these steps, the subscription will not work.
1. Connect to wss
2. Trigger any API, then the subscription will not listen any data.

And here's the result for above steps.
[![enter image description here][2]][2]

As u can see, even though connected to the wss, if i dont send the `Message` by clicked the `Send` button, the subscription will not work.

When I try to implement the subscription in Flutter side, seems only connected to the wss, here's the result.

```dart
flutter: Initialising connection
```

So my question is, how to send the `Message` like from Postman but in Flutter side?

Here's the `Message` data.
```json
{
  "id": "{{$randomUUID}}",
  "payload": {
    "data": "{\"query\":\"subscription updateCheckout { onUpdateCheckout(userId: \\\"{{userId}}\\\") { userId createdAt amount checkoutId maxAllowedAmount maxAvailableAmount message state trancheId }}\"}",
    "extensions": {
      "authorization": {
        "Authorization": "{{cognitoIdToken}}",
        "host": "{{apiHost}}"
      }
    }
  },
  "type": "start"
}
```

Here's the `Schema` from AWS.
```dart
subscription MySubscription {
  onUpdateCheckout(userId: $userId) {
    createdAt
    checkoutId
    maxAllowedAmount
    maxAvailableAmount
    message
    state
    trancheId
  }
}
```

And here's my Flutter code to impl the subscription.
```dart
Future<Map<String, dynamic>> subscription() async {
    try {
      final graphqlEndpoint = 'https://BASEURL/graphql';
      final subscriptionEndpoint =
          'wss://BASEURL/graphql/realtime?header=<EncodedHeader>&payload=e30=';
      var currentToken = _token();

      final HttpLink httpLink = HttpLink(
        graphqlEndpoint,
        defaultHeaders: {
          'Authorization': "Bearer $currentToken",
          'Sec-WebSocket-Protocol': GraphQLProtocol.graphqlWs,
        },
      );

      final WebSocketLink webSocketLink = WebSocketLink(
        subscriptionEndpoint,
        config: SocketClientConfig(
          autoReconnect: true,
          serializer: AppSyncRequest(uuid: 'uuid', token: currentToken),
          inactivityTimeout: const Duration(seconds: 60),
          headers: kIsWeb
              ? null
              : {
                  'Authorization': "Bearer $currentToken",
                  'Sec-WebSocket-Protocol': GraphQLProtocol.graphqlWs,
                },
          initialPayload: {
            'Authorization': currentToken,
          },
        ),
        subProtocol: GraphQLProtocol.graphqlWs,
      );

      final AuthLink authLink =
          AuthLink(getToken: () => 'Bearer $currentToken');

      final Link linkSplitted = authLink.split(
        (request) => request.isSubscription,
        webSocketLink,
        httpLink,
      );

      final graphQLCache = GraphQLCache();

      final client = GraphQLClient(
        link: linkSplitted,
        cache: graphQLCache,
        defaultPolicies: DefaultPolicies(
          watchQuery: Policies(fetch: FetchPolicy.noCache),
          query: Policies(fetch: FetchPolicy.noCache),
          mutate: Policies(fetch: FetchPolicy.noCache),
          subscribe: Policies(fetch: FetchPolicy.noCache),
        ),
        alwaysRebroadcast: true,
      );

      const checkOutSubscription = r'''
subscription MySubscription {
  onUpdateCheckout(userId: $userId) {
    createdAt
    checkoutId
    maxAllowedAmount
    maxAvailableAmount
    message
    state
    trancheId
  }
}
''';

      final options = SubscriptionOptions(
        document: gql(checkOutSubscription),
        variables: {
          "userId": "userId",
        },
      );

      final result = client.subscribe(options);
      Map<String, dynamic> data = {};
      result.listen(
        (event) {
          // not triggered
          data = event.data ?? {};
          if (data.isNotEmpty) {
            // not triggered
          }
        },
        cancelOnError: true,
      );

      return Future.value(data);
    } on Exception {
      rethrow;
    }
  }
```

  [1]: https://i.stack.imgur.com/fIPiq.png
  [2]: https://i.stack.imgur.com/yENf0.png

**Comment by rrifafauzikomara** [comment] 2023-07-20 10:48
I copy the ws link from console log (IDE) when I running that code, then paste it to Postman, it's success connected. Then I send the `Message` by clicked `Send` button, it's success get the data as well.

Seems the problem is I need to send the `Message` as well like in the Postman, but not sure how to do it on ur pacakge, any suggestion?

**Comment by vincenzopalazzo** [comment] 2023-07-20 11:42
I am not able to see what is the ws server protocol. You are using a recent Apollo Server. you are using the wrong protocol

**Comment by rrifafauzikomara** [comment] 2023-07-20 11:56
how i can get the `ws server protocol`? I do not understand what u mean, basically, I just follow ur example from here: https://github.com/zino-hofmann/graphql-flutter/tree/main/examples/starwars

but adding some extra code like header, token, etc. I already share all my code above.

Yea from the postman I can get the data because I can send the `Message` by clicked the `Send` button, but how to do it in ur package?

**Comment by vincenzopalazzo** [comment] 2023-07-20 12:20
No please no screenshot, try to change the protocol with the second one and see the server has the new protocol enabled

**Comment by rrifafauzikomara** [comment] 2023-07-20 12:28
So you hope to understand other developer's problems that use ur package without wanting to see the problem? lol

Change protocol to what? in postman, we use that on the header. In my example code above, I use it as well. And for the ws link we use the same for both flutter code and also postman.

```dart
ws link: wss://BASEURL/graphql/realtime?header=<EncodedHeader>&payload=e30=
ws protocol: graphql-ws
```

**Comment by vincenzopalazzo** [comment] 2023-07-20 12:46
>So you hope to understand other developer's problems that use ur package without wanting to see the problem? lol

You are asking to me to spend time on your problem without know what ws protocol your server speak, by putting a couple of picture together and without know that the library support another protocol (and this mean that you never see the docs) https://github.com/zino-hofmann/graphql-flutter/blob/71d7502dec9336fa72d60d44780294ba01fde7ae/packages/graphql/lib/src/links/websocket_link/websocket_client.dart#L175

every time I regret spending some time on an issue without reproducer. So if you want me to see the problem you need to reproduce an issue with an example that I can run.

P.S: It is missing also the library version, so this is not a bug report, but a consultancy request it you want it you should consider using the email.

Cheers

**Comment by rrifafauzikomara** [comment] 2023-07-20 14:18
Sorry about that, prev I don't understand what `ws` meant, but if u see my code and also I already share it with u right, the `ws protocol` u mean was `graphql-ws` or `GraphQLProtocol.graphqlWs`.

 >by putting a couple of picture together

Like I said before right, the subscription working on Postman, then I want to explain it to u so I put a couple of pictures together with some description about that pictures, but u say `Sorry I do not know what Send a message means!` :(. Then how I can explaint the Postman and my case to u? coz the `Message` and `Send` what I mean before is only available on the screenshot :(.

But yeah nvm, thanks for spending ur time to take a look on my issue. The problem before it's not because `ws protocol` i think, but because I don't add `connectFn` in the `WebSocketLink`. After I add this, now I can get the data from subs. But seems got another error from that.

```dart
flutter: Rifa 3: {"type":"connection_ack","payload":{"connectionTimeoutMs":300000}}
flutter: Rifa 3: {"type":"ka"}
flutter: Rifa 3: {"type":"error","payload":{"errors":[{"errorType":"UnsupportedOperation","message":"unknown not supported through the realtime channel"}]}}
```

Is this error coming from my server or from the package (need more setup)?

**Comment by vincenzopalazzo** [comment] 2023-07-20 14:36
I am closing this because you solved the problem by looking at your code. feel free to if you had a reproducer

**Closed by vincenzopalazzo** 2023-07-20 14:36 UTC
Labels: needs more info, :hourglass: reproduction needed, :zap: websocket, Priority: Waiting to be assigned
