### ISSUE TITLE
Minor Dart SDK compatibility issue (3.0.0 -> 3.0.3)

### ISSUE THREAD

**Issue by ITP2023** [zino-hofmann/graphql-flutter#1347] opened 2023-06-12 19:13 UTC
**minor dart sdk compatibility issue**
Tried adding the `graphql` and `graphql_flutter` to my project but the following error showed up:
```
The current Dart SDK version is 3.0.3.

Because graphql >=5.2.0-beta.2 <5.2.0-beta.3 requires SDK version >=2.15.0
  <=3.0.0 and graphql >=5.2.0-beta.3 depends on http ^0.13.0, graphql
  >=5.2.0-beta.2 requires http ^0.13.0.
And because graphql <5.0.0-beta.1 doesn't support null safety and graphql
  >=5.0.0-beta.1 <5.2.0-beta.2 depends on http ^0.13.0, every version of graphql
  requires http ^0.13.0.
So, because app depends on both http ^1.0.0 and graphql any, version
  solving failed.

The lower bound of "sdk: '>=1.19.0 <2.0.0 or >=2.2.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
```
**To Reproduce**
running `flutter pub add <graphql|graphql_flutter>`

**Note**
I think it's due to the package only being compatible with Dart SDK 3.0.0 but I am currently working with v3.0.3?
Any thoughts on this?

**Comment by vincenzopalazzo** [comment] 2023-06-12 20:06
Is it your dart version inside the project? or do you need to install the last version?

**Comment by ITP2023** [comment] 2023-06-13 06:16
> Is it your dart version inside the project? or do you need to install the last version?

I have only Dart v3.0.3 in both projects

**Comment by vincenzopalazzo** [comment] 2023-06-13 09:53
Do you have the last packages beta too?

**Comment by vincenzopalazzo** [comment] 2023-07-20 12:03
Closing because I suspect the issue is fixerd

**Closed by vincenzopalazzo** 2023-07-20 12:03 UTC
