### ISSUE TITLE
NoSuchMethodError: The getter 'options' was called on null

### ISSUE THREAD

**Issue by fmolina199** [zino-hofmann/graphql-flutter#574] opened 2020-02-29 06:14 UTC
**Describe the bug**

When calling the `fetchMore` function sometimes the `observableQuery` is null and the following exception is thrown: 
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'options' was called on null.
Receiver: null
Tried calling: options
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      QueryManager.addQueryResult (package:graphql/src/core/query_manager.dart:243:25)
#2      ObservableQuery.fetchMore (package:graphql/src/core/observable_query.dart:172:20)
<asynchronous suspension>
#3      EventList.build.<anonymous closure>.<anonymous closure> (package:flutter_app/widgets/list/list_view/event_list.dart:64:24)
#4      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
#5      _rootRun (dart:async/zone.dart:1122:38)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _CustomZone.bi<…>
```

**To Reproduce**
1. Call `fetchMore`
2. The attribute option is called for `observableQuery`, which is null 

**Expected behavior**
The variable `observableQuery` should be validated or the null operator `?` should be used to return null.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.3

**Smartphone (please complete the following information):**
 - Device: iOS Simulator - iPhone 11 Pro Max 
 - OS: iOS
 - Version 13.3

Please let me know if you need any further information.

**Comment by ahmedB7r** [comment] 2020-04-04 12:59
+1

**Comment by micimize** [comment] 2020-05-09 22:47
@fmolina199 some example code would be helpful. `observableQuery` should never be null when it's passed in, but maybe the `Query` widget is being deleted by flutter, thus deleting the `observableQuery`?

**Comment by devakrishna33** [comment] 2020-06-03 19:53
Any update on this? Having similar problem

**Comment by micimize** [comment] 2020-06-03 20:47
@devakrishna33 please provide a code sample and/or more context

**Comment by devakrishna33** [comment] 2020-06-03 20:53
`import "package:flutter/material.dart";
import "package:graphql_flutter/graphql_flutter.dart";

import "./Article.dart";
import "../providers/api/queries.dart";
import "../screens/ArticleScreen.dart";
import "../providers/localization.dart";

class Articles extends StatefulWidget {
  final String sort;
  final String query;
  final bool mainPage;
  final bool searchPage;
  final String type;

  Articles({
    this.sort,
    this.query = "",
    this.mainPage = false,
    this.searchPage = false,
    this.type,
  });

  @override
  _ArticlesState createState() => _ArticlesState();
}

class _ArticlesState extends State<Articles> {
  bool _loading = false;
  bool _done = false;

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Query(
      options: QueryOptions(
        documentNode: gql(GET_ARTICLES),
        variables: {
          "sort": widget.sort,
          "offset": 0,
          "language": AppLocalizations.of(context).translate("id"),
          "query": widget.query,
          "type": widget.type,
        },
      ),
      builder: (QueryResult result,
          {VoidCallback refetch, FetchMore fetchMore}) {
        if (result.hasException) {
          return Text(result.exception.toString());
        }

        List articles = result.data != null ? result.data["getArticles"] : [];

        if ((articles == null || articles.length == 0) && result.loading) {
          return Center(
            child: CircularProgressIndicator(),
          );
        }

        return NotificationListener<ScrollNotification>(
          onNotification: (ScrollNotification scrollInfo) {
            if (scrollInfo.metrics.pixels <=
                    scrollInfo.metrics.maxScrollExtent &&
                !result.loading &&
                !_loading &&
                !_done) {
              _loading = true;
              FetchMoreOptions opts = FetchMoreOptions(
                variables: {
                  "sort": widget.sort,
                  "offset": articles.length,
                  "language": AppLocalizations.of(context).translate("id"),
                  "query": widget.query,
                  "type": widget.type,
                },
                updateQuery: (previousResultData, fetchMoreResultData) {
                  _loading = false;
                  if (fetchMoreResultData["getArticles"].length == 0) {
                    _done = true;
                    return previousResultData;
                  }
                  final List<dynamic> articles = [
                    ...previousResultData["getArticles"] as List<dynamic>,
                    ...fetchMoreResultData["getArticles"] as List<dynamic>
                  ];

                  fetchMoreResultData["getArticles"] = articles;

                  return fetchMoreResultData;
                },
              );
              fetchMore(opts);
            }
            return true;
          },
          child: ListView.builder(
            itemCount: (_done)
                ? articles.length
                : articles.length >= 5 ? articles.length + 1 : articles.length,
            itemBuilder: (context, index) {
              if (index == articles.length) {
                return Center(
                  child: Padding(
                    padding: EdgeInsets.all(30),
                    child: CircularProgressIndicator(),
                  ),
                );
              }
              final article = articles[index];
              return InkWell(
                onTap: () => Navigator.of(context).pushNamed(
                  ArticleScreen.routeName,
                  arguments: article["id"],
                ),
                child: Article(
                  article,
                  refetch,
                ),
              );
            },
          ),
        );
      },
    );
  }
}
`

This is my code, the problem occurs with the fetch more in the listener, the error is "NoSuchMethodError: The getter 'options' was called on null",. In my app there are 3 tabs each will use the above widget with different parameters. When I navigate to a new tab while the previous tab was loading the fetchmore it shows this error.

**Comment by devakrishna33** [comment] 2020-06-03 21:18
Found the issue, the widget was getting destroyed before the fetchmore function returns, is there any way to solve it?. Right now I used the keepalive widget, it would be nice to have a check for observableQuery != null before writing to cache.

**Comment by MattGson** [comment] 2020-08-03 23:13
Any updates on this? `fetchmore` is pretty much unusable due to this.

**Comment by micimize** [comment] 2020-08-03 23:36
@MattGson you could try the custom widget approach above. Even if my conjecture isn't correct, it'd be a good starting point for troubleshooting what exactly the issue is in your specific context

**Comment by MattGson** [comment] 2020-08-10 21:09
@micimize I tried to do this but I had issues importing `import 'package:graphql/internal.dart';`

**Comment by budde377** [comment] 2022-04-23 07:33
Major refactors have happened since this issue was reported. I'll close this for now, please let me know if this still happens.

**Closed by budde377** 2022-04-23 07:33 UTC
